version: "3"

services:
  bot:
    image: py-bot
    container_name: py-bot
    restart: always

  postgres:
    image: postgres
    container_name: py-bot-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postg
    volumes:
      - pgdata:/var/lib/postgresql/data

# TODO prolly remove this in the future
volumes:
  pgdata:
