services:
  db:
    image: postgres
    container_name: py-bot-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postg
      POSTGRES_DB: py-bot-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    image: py-bot
    container_name: py-bot
    restart: always
    build:
      dockerfile: Dockerfile
    depends_on:
      - db

volumes:
  postgres_data: